# Generated by Django 3.1.2 on 2020-11-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_loacation', models.CharField(max_length=60)),
                ('sender_phone_number', models.CharField(max_length=20)),
                ('reciver_name', models.CharField(max_length=30)),
                ('reciver_email', models.EmailField(max_length=254)),
                ('reciver_loacation', models.CharField(max_length=60)),
                ('reciver_phone_number', models.CharField(max_length=20)),
                ('product_weight', models.FloatField()),
                ('product_type', models.CharField(max_length=60)),
                ('product_date', models.DateField()),
                ('product_is_paid', models.BooleanField()),
                ('product_id', models.CharField(blank=True, default='4690046145', editable=False, max_length=10, unique=True)),
            ],
        ),
    ]
