# Generated by Django 3.1.2 on 2020-11-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201116_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='4340119526', editable=False, max_length=10, unique=True),
        ),
    ]
