# Generated by Django 3.1.2 on 2020-11-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201116_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='3107481736', editable=False, max_length=10, unique=True),
        ),
    ]
