# Generated by Django 3.1.2 on 2020-11-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20201118_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='1872465853', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(blank=True, default='3475314274', editable=False, max_length=10, unique=True),
        ),
    ]
