# Generated by Django 3.1.2 on 2020-11-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20201118_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='1475563373782949', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(default='432945767450372', max_length=16),
        ),
    ]
