# Generated by Django 3.1.2 on 2020-11-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20201118_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='2470318218382808', max_length=10),
        ),
    ]
