# Generated by Django 3.1.2 on 2020-11-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20201118_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='563349499177202', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('khulna', 'khulna')], default='khulna', max_length=6),
        ),
    ]
