# Generated by Django 3.1.2 on 2020-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20201118_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reciver_loacation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sender_loacation',
        ),
        migrations.AddField(
            model_name='product',
            name='reciver_location',
            field=models.CharField(choices=[('khulna', 'khulna'), ('dhaka', 'dhaka')], default='khulna', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sender_location',
            field=models.CharField(choices=[('khulna', 'khulna'), ('dhaka', 'dhaka')], default='khulna', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='5248869405261924', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('khulna', 'khulna'), ('dhaka', 'dhaka')], default='khulna', max_length=20),
        ),
    ]
