# Generated by Django 3.1.2 on 2020-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20201118_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='3630249905', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='reciver_location',
            field=models.CharField(choices=[('dhaka', 'dhaka'), ('gazipur', 'gazipur'), ('mymensingh', 'mymensingh'), ('shariatpur', 'shariatpur'), ('faridpur', 'faridpur'), ('tangail', 'tangail'), ('jessore', 'jessore'), ('jhenaidaha', 'jhenaidaha'), ('magura', 'magura'), ('bagerhat', 'bagerhat'), ('khulna', 'khulna'), ('nowapara', 'nowapara'), ('shatkhira', 'shatkhira'), ('kushtia', 'kushtia'), ('kumarkhali', 'kumarkhali'), ('dinajpur', 'dinajpur'), ('pabna', 'pabna'), ('natore', 'natore'), ('rajshahi', 'rajshahi'), ('rangpur', 'rangpur'), ('sirajgang', 'sirajgang'), ('comilla', 'comilla')], default='khulna', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sender_location',
            field=models.CharField(choices=[('dhaka', 'dhaka'), ('gazipur', 'gazipur'), ('mymensingh', 'mymensingh'), ('shariatpur', 'shariatpur'), ('faridpur', 'faridpur'), ('tangail', 'tangail'), ('jessore', 'jessore'), ('jhenaidaha', 'jhenaidaha'), ('magura', 'magura'), ('bagerhat', 'bagerhat'), ('khulna', 'khulna'), ('nowapara', 'nowapara'), ('shatkhira', 'shatkhira'), ('kushtia', 'kushtia'), ('kumarkhali', 'kumarkhali'), ('dinajpur', 'dinajpur'), ('pabna', 'pabna'), ('natore', 'natore'), ('rajshahi', 'rajshahi'), ('rangpur', 'rangpur'), ('sirajgang', 'sirajgang'), ('comilla', 'comilla')], default='khulna', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('dhaka', 'dhaka'), ('gazipur', 'gazipur'), ('mymensingh', 'mymensingh'), ('shariatpur', 'shariatpur'), ('faridpur', 'faridpur'), ('tangail', 'tangail'), ('jessore', 'jessore'), ('jhenaidaha', 'jhenaidaha'), ('magura', 'magura'), ('bagerhat', 'bagerhat'), ('khulna', 'khulna'), ('nowapara', 'nowapara'), ('shatkhira', 'shatkhira'), ('kushtia', 'kushtia'), ('kumarkhali', 'kumarkhali'), ('dinajpur', 'dinajpur'), ('pabna', 'pabna'), ('natore', 'natore'), ('rajshahi', 'rajshahi'), ('rangpur', 'rangpur'), ('sirajgang', 'sirajgang'), ('comilla', 'comilla')], default='khulna', max_length=20),
        ),
    ]
