# Generated by Django 3.1.2 on 2020-11-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20201119_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_officer',
            field=models.CharField(default='officer', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='4477237963', max_length=10),
        ),
    ]
