# Generated by Django 3.1.2 on 2020-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20201119_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='4517262253', max_length=10, unique=True),
        ),
    ]
