# Generated by Django 3.1.2 on 2020-11-19 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20201119_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=10000000000, unique=True),
        ),
    ]
