# Generated by Django 3.1.2 on 2020-11-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20201126_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_price',
            field=models.FloatField(default=0),
        ),
    ]
