# Generated by Django 3.1.2 on 2020-11-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_auto_20201126_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
