# Generated by Django 3.1.2 on 2020-11-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20201126_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_date',
            new_name='product_date',
        ),
    ]
