# Generated by Django 3.1.2 on 2020-11-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20201126_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_weight',
            new_name='product_weight_in_gram',
        ),
    ]
