# Generated by Django 3.1.2 on 2021-01-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20201202_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_retuned',
            field=models.BooleanField(default=False),
        ),
    ]
