# Generated by Django 3.1.2 on 2021-01-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_product_is_retuned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retuned',
            field=models.BooleanField(default=False),
        ),
    ]
